name: ci

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - "0.8"
        - "0.10"
        - "0.12"
        - "1.8"
        - "2.5"
        - "3.3"
        - "4.9"
        - "5.12"
        - "6.17"
        - "7.10"
        - "8.17"
        - "9.11"
        - "10.21"
        - "11.15"
        - "12.18"
        - "13.14"
        - "14.5"
        include:
        - node-version: "0.8"
          npm-i: mocha@2.5.3
          npm-rm: nyc
        - node-version: "0.10"
          npm-i: mocha@3.5.3
          npm-rm: nyc
        - node-version: "0.12"
          npm-i: mocha@3.5.3 nyc@10.3.2
        - node-version: "1.8"
          npm-i: mocha@3.5.3 nyc@10.3.2
        - node-version: "2.5"
          npm-i: mocha@3.5.3 nyc@10.3.2
        - node-version: "3.3"
          npm-i: mocha@3.5.3 nyc@10.3.2
        - node-version: "4.9"
          npm-i: mocha@5.2.0 nyc@11.9.0
        - node-version: "5.12"
          npm-i: mocha@5.2.0 nyc@11.9.0
        - node-version: "6.17"
          npm-i: mocha@6.2.2 nyc@14.1.1
        - node-version: "7.10"
          npm-i: mocha@6.2.2 nyc@14.1.1
        - node-version: "8.17"
          npm-i: mocha@7.2.0
        - node-version: "9.11"
          npm-i: mocha@7.2.0
        - node-version: "10.21"
          npm-i: browserify
        - node-version: "11.15"
          npm-i: browserify
        - node-version: "12.18"
          npm-i: browserify
        - node-version: "14.5"
          npm-i: browserify
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: ./.github/actions/nvm
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure npm
      run: npm config set shrinkwrap false
    - name: Remove non-test npm modules
      run: npm rm --silent --save-dev beautify-benchmark benchmark
    - name: Remove npm module(s) ${{ matrix.npm-rm }}
      run: npm rm --silent --save-dev ${{ matrix.npm-rm }}
      if: matrix.npm-rm != ''
    - name: Install npm module(s) ${{ matrix.npm-i }}
      run: npm install --save-dev ${{ matrix.npm-i }}
      if: matrix.npm-i != ''
    - name: Setup Node.js version-specific dependencies
      run: |
        # eslint for linting
        # - remove on Node.js < 8
        if [[ "$(cut -d. -f1 <<< "${{ matrix.node-version }}")" -lt 8 ]]; then
          node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
            grep -E '^eslint(-|$)' | \
            sort -r | \
            xargs -n1 npm rm --silent --save-dev
        fi
    - name: Install Node.js dependencies
      run: |
        npm install
    - name: List environment
      id: list_env
      run: |
        echo "node@$(node -v)"
        echo "npm@$(npm -v)"
        npm -s ls
        npm -s ls --depth=0 | awk -F'[ @]' 'NR>1 && $2 { print "::set-output name=" $2 "::" $3 }'
    - name: Run tests
      run: |
        if npm -ps ls nyc | grep -q nyc; then
          npm run test-ci
        else
          npm test
        fi
    - name: Lint code
      if: steps.list_env.outputs.eslint != ''
      run: |
        npm run lint
    - name: Collect code coverage
      uses: coverallsapp/github-action@master
      if: steps.list_env.outputs.nyc != ''
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Uploade code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
